### PR TITLE
hotfix: drop the "build userdocs"

### PR DESCRIPTION
**Pull request by RaitoBezarius**
This unblocks all the PRs, @sonmarcho.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
I will resubmit a proper fix later, but I need to understand why there's a EPERM…

**Comment by sonmarcho** [comment]
There are still issues: do you have an idea of what's going on?

**Comment by RaitoBezarius** [comment]
@sonmarcho Actually, I think this might be the CI setup that never supported another branch like this, it's either a bug inside the setup code of the GitHub actions runner we self host, either you can just nuke the gh-pages branch for the time being and this should repair all of that I'd think (?).

**Comment by sonmarcho** [comment]
What do you mean by "nuke the gh-pages"?

**Comment by RaitoBezarius** [comment]
> What do you mean by "nuke the gh-pages"?

```
git branch -d gh-pages
git push -f
```

something along those lines, just delete the remote gh-pages branch so that on the next clone, there's no tree containing the gh-pages branch

**Comment by RaitoBezarius** [comment]
I don't have permissions to restart a CI build, can you send me which action fail even if the gh-pages branch doesn't exist?

The last run yesterday showed:

```
Run actions/checkout@v4
Syncing repository: AeneasVerif/aeneas
Getting Git version info
Temporarily overriding HOME='/run/github-runner/aeneas-ci/_temp/84fd9ec6-f06b-4a97-a3ed-4a150d0c6912' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/nix/store/jsbha1gg6lzzj7icrg3h0npgm8vwf80c-git-2.45.1/bin/git config --global --add safe.directory /run/github-runner/aeneas-ci/aeneas/aeneas
Deleting the contents of '/run/github-runner/aeneas-ci/aeneas/aeneas'
**Error: File was unable to be removed Error: EACCES: permission denied, rmdir '/run/github-runner/aeneas-ci/aeneas/aeneas/gh-pages/FontAwesome/css'**
``

So I assume by deleting `gh-pages`, it should solve the problem, if not, someone with ssh access needs to remove `gh-pages` directory manually?

**Comment by sonmarcho** [comment]
> I don't have permissions to restart a CI build, can you send me which action fail even if the gh-pages branch doesn't exist?
> 
> The last run yesterday showed:
> 
> ```
> Run actions/checkout@v4
> Syncing repository: AeneasVerif/aeneas
> Getting Git version info
> Temporarily overriding HOME='/run/github-runner/aeneas-ci/_temp/84fd9ec6-f06b-4a97-a3ed-4a150d0c6912' before making global git config changes
> Adding repository directory to the temporary git global config as a safe directory
> /nix/store/jsbha1gg6lzzj7icrg3h0npgm8vwf80c-git-2.45.1/bin/git config --global --add safe.directory /run/github-runner/aeneas-ci/aeneas/aeneas
> Deleting the contents of '/run/github-runner/aeneas-ci/aeneas/aeneas'
> **Error: File was unable to be removed Error: EACCES: permission denied, rmdir '/run/github-runner/aeneas-ci/aeneas/aeneas/gh-pages/FontAwesome/css'**
> ``
> 
> So I assume by deleting `gh-pages`, it should solve the problem, if not, someone with ssh access needs to remove `gh-pages` directory manually?
> ```

This run was performed after I deleted the branch (I manually re-started the CI).

**Comment by sonmarcho** [comment]
@Nadrieril is investigating the issue

**Comment by sonmarcho** [comment]
The CI seems to go through *without those changes*. Closing this for now, we'll re-open it if necessary.

**Pull request closed without merging**
